apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: flex-reisetilskudd-backend
  namespace: flex
  labels:
    team: flex
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  leaderElection: true
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 400m
      memory: 768Mi
  kafka:
    pool: nav-prod
  gcp:
    sqlInstances:
      - type: POSTGRES_11
        databases:
          - name: flex-reisetilskudd-db
            diskAutoresize: true
  accessPolicy:
    outbound:
      external:
        - host: navtestb2c.b2clogin.com
    inbound:
      rules:
        - application: flex-reisetilskudd-backend-proxy

  envFrom:
    - secret: flex-reisetilskudd-backend-serviceuser
    - configmap: loginservice-idporten
  env:
    - name: KAFKA_BOOTSTRAP_SERVERS_URL
      value: SASL_SSL://a01apvl00145.adeo.no:8443,SASL_SSL://a01apvl00146.adeo.no:8443,SASL_SSL://a01apvl00147.adeo.no:8443,SASL_SSL://a01apvl00149.adeo.no:8443

